In [58]:
import numpy as np
import array

In [74]:
a1 = array.array( 'i', [1,2,3,4,21,3])
a2 = array.array( 'f', [10,20,30,40,210,30])

a4 = [1,2,3,4,21,3,10,20,30,40,210,30] 

In [60]:
a3 = my_array('u', ['a','b', 'c'])

In [81]:
np.array( a4).reshape([2,6])

array([[  1,   2,   3,   4,  21,   3],
       [ 10,  20,  30,  40, 210,  30]])

In [88]:
v1.itemsize

8

In [99]:
data = np.linspace(0,100,1000).reshape((100,10))

In [108]:
data.dtype

dtype('float64')

In [105]:
np.savetxt( "saida.txt" ,data, delimiter=";")
data_2 = np.loadtxt( "saida.txt", delimiter=";" )

In [112]:
data[:2]

array([[0.       , 0.1001001, 0.2002002, 0.3003003, 0.4004004, 0.5005005,
        0.6006006, 0.7007007, 0.8008008, 0.9009009],
       [1.001001 , 1.1011011, 1.2012012, 1.3013013, 1.4014014, 1.5015015,
        1.6016016, 1.7017017, 1.8018018, 1.9019019]])

In [113]:
data_2[:2]

array([[0.       , 0.1001001, 0.2002002, 0.3003003, 0.4004004, 0.5005005,
        0.6006006, 0.7007007, 0.8008008, 0.9009009],
       [1.001001 , 1.1011011, 1.2012012, 1.3013013, 1.4014014, 1.5015015,
        1.6016016, 1.7017017, 1.8018018, 1.9019019]])